# Example pipeline: Implement a new feature

name: feature-implementation
description: Multi-stage pipeline for implementing a new feature

workspace:
  path: .

gates:
  go_test:
    type: command
    command: ["go", "test", "./..."]
    workdir: .

stages:
  - name: research
    task_type: research
    adapter: mock
    model: mock-1
    prompt: |
      Research existing patterns and best practices for: {{ .Input }}
      Focus on:
      - Common implementation approaches
      - Potential pitfalls
      - Recommended libraries

  - name: outline
    task_type: outline
    adapter: mock
    model: mock-1
    prompt: |
      Based on the research:
      {{ .Artifacts.research.Text }}

      Create an implementation outline for: {{ .Input }}
      Include:
      - File structure
      - Key functions/classes
      - Data flow

  - name: implement
    task_type: implement
    adapter: mock
    model: mock-1
    prompt: |
      Following this outline:
      {{ .Artifacts.outline.Text }}

      Implement the feature: {{ .Input }}
      Write clean, well-documented code.
    gates:
      - go_test
    max_retries: 1

  - name: review
    task_type: review
    adapter: mock
    model: mock-1
    prompt: |
      Review this implementation:
      {{ .Artifacts.implement.Text }}

      Check for:
      - Correctness
      - Performance issues
      - Security concerns
      - Code quality
