# Example pipeline: Large codebase refactor

name: large-refactor
description: Multi-stage pipeline for large-scale refactoring

workspace:
  path: .

gates:
  go_test:
    type: command
    command: ["go", "test", "./..."]
    workdir: .

stages:
  - name: analyze
    task_type: review
    adapter: mock
    model: mock-1
    prompt: |
      Analyze this codebase for refactoring:
      {{ .Input }}

      Identify:
      - Code smells
      - Duplicated logic
      - Architectural issues
      - Dependencies to update

  - name: plan
    task_type: outline
    adapter: mock
    model: mock-1
    prompt: |
      Based on this analysis:
      {{ .Artifacts.analyze.Text }}

      Create a refactoring plan with:
      - Ordered list of changes
      - Risk assessment for each change
      - Rollback strategies
      - Testing requirements

  - name: refactor
    task_type: refactor
    adapter: mock
    model: mock-1
    prompt: |
      Following this plan:
      {{ .Artifacts.plan.Text }}

      Perform the refactoring on:
      {{ .Input }}

      Make changes incrementally and maintain backwards compatibility where possible.
    gates:
      - go_test
    max_retries: 1

  - name: verify
    task_type: review
    adapter: mock
    model: mock-1
    prompt: |
      Verify this refactoring:

      Original:
      {{ .Input }}

      Refactored:
      {{ .Artifacts.refactor.Text }}

      Confirm:
      - Functional equivalence
      - No regressions introduced
      - Improved code quality
